### ISSUE TITLE
about the map

### ISSUE THREAD

**Issue by allenhsu6** [jvirdi2/A_star_and_Hybrid_A_star#1]
How is a complex obstacle created? For example the case2,3,4.png. Is it manually set the obstacle points in the program? Whether there is a program to randomly generate a map of complex obstacles?

**Comment by jvirdi2** [comment]
Yes, so the version that I put up on GitHub, there you have to manually
enter how obstacles are shaped.

The obstacles in the case images that I have shown were provided to us
separately to test the algorithms

Jasvir
