### ISSUE TITLE
endless loop when gx>=7

### ISSUE THREAD

**Issue by chrisrkr** [jvirdi2/A_star_and_Hybrid_A_star#3]
I tried to find a simple path from sx, sy, stheta= 1, 0, 0 to gx, gy, gtheta = 12, 0, 0. After some searching i found out, that "open_heap" is increasing when gx is 7 or higher. The main result is, that no path is found and no output is generated. waited until open_head list reached a length of around 4000. then stopped the process. EDIT: 'self.euc_dist(chosen_d_node,end) is getting higher and does not near 0 to find a final path. waited around 45 min, then euc_dist reached araound 65, altough x1=1 to x2=12 is only 11.'
is it a mistake of me inputting values outside a specific range or is there an other issue?

**Comment by jvirdi2** [comment]
Sorry for the late reply , but did you get it to work? I didn't get a
chance to see the issue

Best
Jasvir

**Comment by chrisrkr** [comment]
found (my) error (some kind of manual would help)
min and max values for x are defined. if gx (goal) is higher than defined max value of x, than there is no solution found, because an if condition doesn't get True. When gx is inside the defined max values it runs. it should be mentioned that it still runs, even when gx is below the min vaule. seems to be relevant in which direction the search is made (in the direction of positive x, than xMax is relevant, and vise versa)

here the issue-text again:
"I tried to find a simple path from sx, sy, stheta= 1, 0, 0 to gx, gy, gtheta = 12, 0, 0. After some searching i found out, that "open_heap" is increasing when gx is 7 or higher. The main result is, that no path is found and no output is generated. waited until open_head list reached a length of around 4000. then stopped the process. EDIT: 'self.euc_dist(chosen_d_node,end) is getting higher and does not near 0 to find a final path. waited around 45 min, then euc_dist reached araound 65, altough x1=1 to x2=12 is only 11.'
is it a mistake of me inputting values outside a specific range or is there an other issue?"
